/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package lucas.granbery.mensageiro.domain.services.support.graphics.drawable;

public final class R {
    private R() {}

}
